version: '3.9'

services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  app1:
    image: pr5
    restart: on-failure
    volumes:
      - ./static:/app/static
  app2:
    image: pr5
    restart: on-failure
    volumes:
      - ./static:/app/static
  app3:
    image: pr5
    restart: on-failure
    volumes:
      - ./static:/app/static